name: backendCI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: "6.0"

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --dev
        pip install flask
        pipenv install flask pymongo
        pip install pytest
        pip install python-dotenv

    - name: Run app.py
      run: python backend/app.py

    - name: Run pytest
      run: |
        pipenv run pytest






