name: backendCI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --dev
        pipenv install flask pymongo
        pip install pytest
        pip install python-dotenv
        pip install mongodb-community@6.0
        pip start mongodb-community@6.0

    - name: Run app.py
      run: python app.py

    - name: Run pytest
      run: |
        pipenv run pytest






